version: '3.8'

services:
  # Node.js Application
  app:
    build: .
    container_name: blogging-app-server
    restart: always
    ports:
      - "2000:2000"
    environment:
      - PORT=2000
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/blog_db
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=supersecretkey123
      - APP_URL=http://localhost:2000
      - CLIENT_URL=http://localhost:5173
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

  # MongoDB Service
  mongo:
    image: mongo:6
    container_name: blogging-app-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Redis Service
  redis:
    image: redis:alpine
    container_name: blogging-app-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  mongo_data:
